services:
  postgres:
    image: postgres@sha256:e013e867e712fec275706a6c51c966f0bb0c93cfa8f51000f85a15f9865a28cb
    env_file:
      ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma@sha256:1e0b73a187a28757c572acba508c46f48c9e8b0acaf5c20e6d95cdedce1acdf6
    ports:
      - "8001:8000"
    environment:
      IS_PERSISTENT: "TRUE"
      ANONYMIZED_TELEMETRY: "FALSE"
    volumes:
      - chroma-data:/chroma/chroma

  redis:
    image: redis@sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: rag-backend:local
    ports:
      - "8000:8000"
    depends_on:
      - chroma
      - postgres
      - redis
    env_file:
      ./server/.env
    environment:
      PYTHONUNBUFFERED: "1"
      DO_NOT_TRACK: "true"
      CHROMA_HOST: chroma
      CHROMA_PORT: "8000"
      CHROMA_COLLECTION_NAME: rag_documents
      UPLOAD_DIR: /workspace/uploads
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - upload-data:/workspace/uploads
      - unstructured-cache:/home/notebook-user/.cache

  celery_worker:
    image: rag-backend:local
    build:
      context: ./server
      dockerfile: Dockerfile
    command: celery -A celery_app.celery_app worker --loglevel=info --concurrency=1
    depends_on:
      - chroma
      - postgres
      - redis
    env_file:
      ./server/.env
    environment:
      PYTHONUNBUFFERED: "1"
      DO_NOT_TRACK: "true"
      CHROMA_HOST: chroma
      CHROMA_PORT: "8000"
      CHROMA_COLLECTION_NAME: rag_documents
      UPLOAD_DIR: /workspace/uploads
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - upload-data:/workspace/uploads
      - unstructured-cache:/home/notebook-user/.cache

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: rag-frontend:local
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data:
  chroma-data:
  upload-data:
  unstructured-cache:
  redis-data:
